package hotelmgmttuto;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

import hotelmgmttuto.UserDAO;
import hotelmgmttuto.UserVO;

/**
 *
 * @author rkddm
 */

public class Join extends javax.swing.JFrame {
UserDAO dao = new UserDAO();
    /**
     * Creates new form join
     */
    public Join() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pwdField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pwdcheckField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        btnJoin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        eMailField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("회원가입");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 15, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("연락처");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        pwdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdFieldActionPerformed(evt);
            }
        });
        jPanel2.add(pwdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 236, -1));

        jLabel3.setText("비밀번호");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 76, -1));
        jPanel2.add(pwdcheckField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 236, -1));

        jLabel4.setText("비밀번호 확인");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        jPanel2.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 236, -1));

        jLabel5.setText("성명");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 76, -1));

        btnCheck.setText("중복확인");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        jPanel2.add(btnCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 95, -1));

        btnJoin.setText("회원가입");
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });
        jPanel2.add(btnJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 110, -1));

        btnCancel.setText("취소");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 110, -1));

        jLabel2.setText("이메일");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 76, -1));
        jPanel2.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 236, -1));

        eMailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMailFieldActionPerformed(evt);
            }
        });
        jPanel2.add(eMailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 236, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eMailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMailFieldActionPerformed

    private void pwdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdFieldActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
   
    String idSearch = eMailField.getText();
    System.out.println(idSearch.length());
    if(idSearch.equals("")) {
            JOptionPane.showMessageDialog(this, "이메일을 입력하셔야 합니다");

    }  
    else {
            List<UserVO> result = dao.getidCheck(idSearch);
            if(result.size()==0) {
                    JOptionPane.showMessageDialog(this, "사용 가능한 아이디 입니다");
                    btnJoin.setEnabled(true);
                    eMailField.setEnabled(false);
            } else {
                    JOptionPane.showMessageDialog(this, "등록되어 있는 이메일 입니다");
            }

    } 
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed

        
        
    String id = eMailField.getText();
    String password = pwdField.getText();
    String pwdCheck = pwdcheckField.getText();
    if(id.equals("")) {
            JOptionPane.showMessageDialog(this, "이메일을 입력하셔야 합니다");
    } else if(password.equals("")) {
            JOptionPane.showMessageDialog(this, "비밀번호를 입력하셔야 합니다");
    } else if(password.length()<6 || password.length()>20) {    
            JOptionPane.showMessageDialog(this, "비밀번호는 6자리 이상, 20자리 이하만 가능 합니다.");
    } else if(pwdCheck.equals("")) {
            JOptionPane.showMessageDialog(this, "비교할 비밀번호를 입력해 주시기 바랍니다");
    } else if(!password.equals(pwdCheck)) {
            JOptionPane.showMessageDialog(this, "비밀번호가 일치하지 않습니다");
    } else if(checkPWDMethod(password)==1) {
            JOptionPane.showMessageDialog(this, "비밀번호 특수문자는 !@#만 포함 가능 합니다");
    } else if(nameField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "이름(한글)을 입력하셔야 합니다");
    }  else if(phoneField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "연락처를 입력하셔야 합니다");
    } else if(emailCheck(eMailField.getText())==1){
            JOptionPane.showMessageDialog(this, "잘못된 이메일을 입력하셨습니다");					
    } else {
            UserVO vo = new UserVO(eMailField.getText(),pwdField.getText(),nameField.getText(),phoneField.getText());

            int result = dao.SignUpInsert(vo);
            if(result>0) { // 회원등록 성공함
                    JOptionPane.showMessageDialog(this, "회원가입에 성공하였습니다\n원활한 이용을 위하여\n로그인 해주시기 바랍니다");
                    new Login().setVisible(true);
                    this.dispose();
            } else { //회원등록 실패함
                    JOptionPane.showMessageDialog(this, "회원가입에 실패하였습니다\n 관리자에게 문의해 주시기 바랍니다");
            }
            dispose();
            
    }
        
        

    }	
	public int checkIDMethod(String id) {
		int check= 0;
		char alpha;
		int code;
		for(int i=0; i<id.length(); i++) {
			alpha = id.charAt(i);
			code = (int)alpha;
			if(code>=0 && code<=47 || code>=58 && code<=63 || code>=91 && code <=96 || code>=123 && code <= 127) {
				check = 1;
			}
		}
		return check;
	}
	
	public int checkPWDMethod(String pwd) {
		int check= 0;
		char alpha;
		int code;
		for(int i=0; i<pwd.length(); i++) {
			alpha = pwd.charAt(i);
			code = (int)alpha;
			if(code>=0 && code<=32 || code>=36 && code<=47 || code>=58 && code<=63 || code>=91 && code <=96 || code>=123 && code <= 127) {
				check = 1;
				
			}
		}
		return check;
	}
	
	public int emailCheck(String email) {
		int emailCheck =0;
		// email에 @ 가 있는가? email에 .이 올바르게 있나 ? email에 특수문자가 있나?
		if(email.indexOf("@")== -1 || period(email)==true ||specialCharacter(email)==0) {
			emailCheck = 1;
		}
		// 0이면 이메일 체크결과 이상 없다, 1이면 이상 있다
		return emailCheck;
	}
	
	public Boolean period(String email) {
		String spl[] = email.split("@");
		// split은 @ 기준으로 앞뒤로 나눈다
		// spl[0] = id,  spl[1] = email주소
		int num = spl[1].lastIndexOf(".") - spl[1].indexOf("."); // last와 index의 값차이를 검사
		
		boolean clear = false;
		
		// "@"의 앞단 "." 있는지 확인
		if(spl[0].indexOf(".")==-1);
		else clear=true;
		
		// "@"의 뒷단 도메인 부분의 "." 들의 간격이 4칸이상 떨어지면 이메일이 아니다
		if(num <4);
		else clear = true;
		
		// 이메일에 .이 잘못되었을 경우 true를 보낸다
		return clear;
	}
	
	public int specialCharacter(String email) {
		String text[] = { "#", "!","$","%","^","&","*","(",")","-", "_","+","=",",","[","]","{","}",":",";","'","?","<",">"};
		
		int result = 0;
		for(int i=0; i<text.length; i++) {
			if(email.indexOf(text[i]) == -1) {
				result = 1;
			} else {
				break;
			}
		}
		// 이메일 검사했을때 특수문자가 있으면 1을 보내고 없으면 0을 보낸다
		return result;
	
	
    }//GEN-LAST:event_btnJoinActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Join().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnJoin;
    private javax.swing.JTextField eMailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField pwdField;
    private javax.swing.JTextField pwdcheckField;
    // End of variables declaration//GEN-END:variables
}
