/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author rkddm
 */
package hotelmgmttuto;

import hotelmgmttuto.UserDAO;
import hotelmgmttuto.UserVO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.util.Random;

public class Login extends javax.swing.JFrame {
    UserDAO dao = new UserDAO();
    int loginFlag = 0;
    private String captchaText;
    private JLabel captchaLabel;
    
   
    public Login() {
        initComponents();
        generateCaptcha();
    }
    private boolean validateLogin(String enteredEmail, String enteredPassword) {
        UserDAO dao = new UserDAO();
        List<UserVO> userList = dao.getUserByEmailAndPassword(enteredEmail, enteredPassword);

        return !userList.isEmpty(); // 사용자 리스트가 비어있지 않으면 로그인 성공
    }
     private void generateCaptcha() {
        captchaText = generateCaptchaText();
        BufferedImage captchaImage = generateCaptchaImage(captchaText);
        if (captchaLabel != null) {
            panCapcha.remove(captchaLabel);
        }
        captchaLabel = new JLabel(new ImageIcon(captchaImage));
        panCapcha.add(captchaLabel);
        panCapcha.revalidate();
        panCapcha.repaint();
    }
       private String generateCaptchaText() {
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        StringBuilder captchaText = new StringBuilder();
        Random rnd = new Random();
        while (captchaText.length() < 6) {
            int index = (int) (rnd.nextFloat() * chars.length());
            captchaText.append(chars.charAt(index));
        }
        return captchaText.toString();
    }

    private BufferedImage generateCaptchaImage(String captchaText) {
        BufferedImage img = new BufferedImage(160, 60, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = img.createGraphics();
        g2.setFont(new Font("Serif", Font.BOLD, 40));
        g2.setColor(Color.WHITE);
        g2.fillRect(0, 0, 160, 60);
        g2.setColor(Color.BLACK);
        g2.drawString(captchaText, 15, 30);
        g2.dispose();
        return img;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCapcha = new javax.swing.JButton();
        txtCapcha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtPw = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panCapcha = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("로그인");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 90, 30));

        btnCapcha.setText("확인");
        btnCapcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapchaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCapcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 63, -1));

        txtCapcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapchaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCapcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 165, -1));

        jLabel4.setText("보안문자를 입력해주세요.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        btnLogin.setText("로그인");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 76, -1));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("회원가입");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 100, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 200, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 200, -1));

        jLabel2.setText("이메일 :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jLabel3.setText("비밀번호 :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        panCapcha.setBackground(new java.awt.Color(0, 102, 102));
        panCapcha.setLayout(new java.awt.BorderLayout());
        jPanel1.add(panCapcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 216, 100));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 700, 370));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCapchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapchaActionPerformed

    private void btnCapchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapchaActionPerformed
        // TODO add your handling code here:
         if (txtCapcha.getText().equals(captchaText)) {
            JOptionPane.showMessageDialog(this, "인증성공");
            loginFlag = 1;
        } else {
            JOptionPane.showMessageDialog(this, "보안문자가 틀립니다");
            generateCaptcha();
        }
    }//GEN-LAST:event_btnCapchaActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       String enteredEmail = txtEmail.getText();
        String enteredPassword = txtPw.getText();

        // 여기에 로그인 처리 코드 추가
        if (validateLogin(enteredEmail, enteredPassword) & loginFlag == 1) {
            JOptionPane.showMessageDialog(this, "로그인 성공");
            Rooms.getFrames();
            dispose();
            Rooms mainFrame = new Rooms();
            mainFrame.setVisible(true);
        }else if (loginFlag != 1)
        {
            JOptionPane.showMessageDialog(this, "캡챠인증을 진행 해주세요");

        }
        else {
            JOptionPane.showMessageDialog(this, "로그인 실패");
            loginFlag = 0;
            // 로그인 실패 시 수행할 동작 추가
        }        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Join().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapcha;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panCapcha;
    private javax.swing.JTextField txtCapcha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPw;
    // End of variables declaration//GEN-END:variables
}
